version: '3'

services:
  app:
    image: movie-crawler
    container_name: movie-crawler
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME= crawler_admin  
      - MONGO_INITDB_ROOT_PASSWORD= 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 
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongodb_data: 