version: '3'

services:
  app:
    image: movie-crawler
    container_name: movie-crawler
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
